---
title: "Frustrations Along the Way"
author: "Andrew Borozan"
date: "`r Sys.Date()`"
output: 
  html_document:
     toc: FALSE
editor_options: 
  markdown: 
    wrap: sentence
---

The "hero's journey" stories always neglect to leave out the minor details and difficulties, and understandably so: nobody wants to watch a movie where Frodo is continually itching bug bites, or Batman is plagued by chaffing.
Obstacles are present but they typically come in the grand, overarchingly thematic form; evil embodied, a treacherous landscape, or a malady to overcome.
Minor annoyances are cast to the background, if they are there at all.

But minor annoyances, miniature obstacles are very real in the inglorious, non-cinematic, real life hero journey.
I don't have a grotesque villain to vanquish; I am staring down a website that won't work.
I don't have an undulous New Zealand landscape to traverse, I simply can't figure out how to code something.
These are rocks in the shoe that slow down the process.
Yes, there is a grand narrative present in which I am making a heroic effort to change careers, and there is an ultimate and final goal of breaking into a new industry.
And there are massive, sweeping themes like perseverance and courage and all the other qualities that attend the hero's journey narrative.
But I am finding that I don't really focus on that stuff as much; I am typically not thinking about the grand themes in a hero's journey narrative.
My attention is consumed more by the day-to-day challenges, the smaller scale difficulties and frustrations that make this journey laborious.

In reflecting on these "mini-challenges" and frustrations, I realize they can be categorized and abstracted.
There are patterns evident that, while not monumental, like the enduring themes of good and evil and perseverance, are nevertheless real and impactful.
Here are some of the themes and characteristics present in these common frustrations, these daily hurdles, that bother and wear down on the long quest from one career to another.

### Expected to Know Everything 

There was a lot to know as a teacher.
Not only do you have to know your content well (I had to be an expert in every era as a history teacher, teaching content that spanned from the birth of humanity to current events. I was expected to know everything about the Third Crusade and Mao's Cultural Revolution concurrently....along with a million other things), you have to be knowledgeable of reading strategies, writing strategies, classroom management techniques, curriculum goals, grading policies and procedures (and the platforms in which to record grades, which seemed to change yearly), vertical alignment (what did the incoming grade 9 students already learn?) and horizontal alignment (what are the grade 9 students doing in their literature class and does anything we are teaching in here align with that material?), child protection procedures, school safety procedures...on and on.
This is only a peek at all the stuff you need to know as a teacher.

I didn't know all of this stuff before I started teaching though.
I learned much of it on the job (I didn't know anything about the Russian Revolution before I started teaching it...now I am very knowledgeable on the topic).
There was an understanding that you have some background knowledge and skill and that a lot of the first couple of years was learning the ropes.
That is why there were mentor programs for new teachers in the schools I was in; lots of learning happened on the job.
The first couple years of teaching was Hobbesian - solitary, poor, nasty, brutish, and...well, not too short I guess - but there was the understanding that you didn't start a finished product.

From the outside looking in, the field of data analytics seems less...let's say "forgiving".
I look at job postings and the requirements needed for the job and quickly start to despair.

Excel?
Ok, got that one down.
Python or R?
Yeah, I am pretty decent in R.
Need to learn Python as it seems to be the preferred language.
SQL?
I know the basics.
I prefer to use R - you can do all the same things (and more) and seems way more intuitive.
Tableau, PowerBI, Shiny, or Looker?
Tableau, I am ok with.
I looked at PowerBI.
I don't know what Shiny or Looker are.
Azure?
Huh?
AWS?
Nope.
Java?
No thanks, but I'll take a water.
Access?
I know it is a Microsoft thing.
Agile/scrum process and product backlog grooming?
Are those real things?
Oracle?
At Delphi?
I've been there.
Master degree in Math, Statistics, Economics, or Computer Science?
Sorry, unfortunately mine is in "Theological Arts" - which I don't even know what that means; I took a lot of history and philosophy courses though.

These, and about 80 other acronyms, are all listed for entry level positions.
I feel like I have to know everything about everything in the field before I can even apply to a bottom of the totem pole position.

And so I try to learn it all.
I take courses on Coursera and do some of the tracks on DataCamp.
I watch endless YouTube videos and read articles until my eyes bleed.
A lot of times you need to know one thing to know another thing.
For example, I had to figure out how to use GitHub to host this site...but I needed to become familiar with RMarkdown first...and GitKraken to push my changes in R to my GitHub repository...but then learned GitHub Desktop could do the same thing GitKraken can do (and was a little easier)....but I can also push my changes right in RStudio to my GitHub repository...but I just learned GitHub Desktop so I'll just stick with that for now.

Or I have to learn how to navigate SQL Server, so I watch an hour long YouTube video on that.
But then I am taking a class on Coursera and they want me to integrate something with Microsoft Access, so I go over to Microsoft and watch their videos and read their articles for Access.
But then the next class I take is on Udemy and they are working with PostgreSQL and so I have to download that and learn that interface.
I have to know 5 different SQL platforms...and at the end of it I still don't feel like I am an expert at SQL or any particular platform.

I'll spend a month neck deep in SQL only to turn my attention to Tableau for a month and then head over to R and play around in there for a month, only to return to SQL and realize that while some of the basics concepts I have retained (and even understand better thanks to working in R), I have forgotten a lot because I haven't touched it in a couple of months.

The point here is that when you have to seemingly know everything...you end up not knowing very much.
I have a passing knowledge of many things - I know what some things look like - but I am not an expert in any.
Jack of all trades, master of none.

And it feels like that isn't true to the scene on the job anyway (of course, I wouldn't know yet): are you going to be working with 4 different languages and 8 different platforms all the time?
You have to be an expert in all of these things?
Seems like a lot.

I want to learn as much as I can, I really like this stuff, but one gets overwhelmed trying to break into the field after seeing the laundry list of requirements and expertise needed to even gain entry.
Is there learning/training on the job, or do I just have to be a GI out of the box?

I am encouraged by this however: I have a family member, one of those "Christmas Cousins" that you see about twice a year around Christmas and one other holiday (take your pick between Easter and Thanksgiving), who is in the field.
He is currently getting his masters in data science and we have been talking a little bit about my transition into the field.
He said, "It is probably a little overwhelming huh?" That's an understatement.
He continued, "Don't worry about it. I have a professor right now, a PhD in this stuff and he said even he can't keep up with everything. New platforms, new skills, it is impossible to be good at all of it." I was encouraged by this, and others who have said that once you get a position you will be working primarily with a couple of platforms.

But I am not in that position yet.
And it seems like to get to that position, I have to do the very opposite and know everything about everything.

So this is the first minor (to major) frustration: as I learn all of this stuff, I don't really know what I am supposed to know.
But I just keep my head down, keep doing courses on Coursera and hope somebody will take that as a positive signal of competence.

### Too Much Information 

Related to the first frustration, when you try to learn everything there is simply too much information.
The information nuclear bomb that is the internet probably stymies efforts to learn in a coordinated, linear fashion, as the internet encourages an addled, discontinuous attention.
It isn't only the copious amount of information on the internet (yes, that is obviously a problem), it is the uncurated nature of it.
The internet is all information at once, not the slow, methodical, linear drip our brains were designed for.

This has given me a different perspective on formal education.
For all of the problems with any and all education systems, one thing education at least attempts to do is present information in a coordinated and logical manner.
While standards and benchmarks may be too rigid or ill-conceived (soon, math standards for 2nd graders will be requiring pre-calc) at least the idea behind them stems from a belief that learning happens somewhat (but not entirely) methodically.
Education, then, is in the curation business.
This allows for a much more manageable learning environment...

...as opposed to the internet which is a disorganized mess of information.
Even when certain sites attempt curation - building out sections for different topics or tracks or programs - you are only a click away from a whole stream of other content that may or may not be related.
DataCamp does a really good job with their site.
There is a Python section and an R section.
There are tutorials over here and projects over there.
But even with the best of intentions to stick with one track or project and see it through, I find myself wandering to another site, and getting lost in that content, to return (or not) to whatever I started on DataCamp later.
It usually starts in a harmless manner: I have a question about a certain thing, so I stumble over to Google and search away.
I fall down the rabbit hole of this particular topic only to latch onto another question and a tutorial on someone's YouTube channel.
It seems like I am latching on to whatever courier happens to be passing by at the time and riding with them until I see another courier to hook onto.
One imagines Y.T.
in Snow Crash pooning passing cars, only, I never get to my final destination of learning the material I set out to learn.

Because of the nature of the internet and our patterned behavior of interaction with it, information seems to rarely crystallize into knowledge.
We need the slow drip of the old way of doing things, like reading a book, instead of the fire hose of the internet.
Nicholas Carr in his book "The Shallows" makes this very point:

> "Imagine filling a bathtub with a thimble; that's the challenge involved in transferring information from working memory into long-term memory. By regulating the velocity and intensity of information flow, media exert a strong influence on this process. When we read a book, the information faucet provides a steady drip, which we can control by the pace of our reading. Through our single-minded concentration on the text, we can transfer all or most of the information, thimbleful by thimbleful, into long-term memory and forge the rich associations essential to the creation of schemas. With the Net, we face many information faucets, all going full blast. Our little thimble overflows as we rush from one faucet to the next. We're able to transfer only a small portion of the information to long-term memory, and what we do transfer is a jumble of drops from different faucets, not a continuous, coherent stream from one source.
>
> The information flowing into our working memory at any given moment is called our "cognitive load." When the load exceeds our mind's ability to store and process the information---when the water overflows the thimble---we're unable to retain the information or to draw connections with the information already stored in our long-term memory.
> We can't translate the new information into schemas.
> Our ability to learn suffers, and our understanding remains shallow.
> Because our ability to maintain our attention also depends on our working memory---"we have to remember what it is we are to concentrate on," as Torkel Klingberg says---a high cognitive load amplifies the distractedness we experience.
> When our brain is overtaxed, we find "distractions more distracting." (Some studies link attention deficit disorder, or ADD, to the overloading of working memory.) Experiments indicate that as we reach the limits of our working memory, it becomes harder to distinguish relevant information from irrelevant information, signal from noise.
> We become mindless consumers of data."
>
> Carr, Nicholas.
> The Shallows: What the Internet Is Doing to Our Brains (pp. 124-125).
> W.
> W. Norton & Company.
> Kindle Edition.

The whole book paints a rather damning picture of the nature of information and knowledge in the age of the internet.
And in my attempt to learn this virgin material, I have to agree with many of Carr's conclusions.
While I am learning a wide breadth of material, I am only learning it on a surface level.
The internet is preventing me from having truly deep knowledge and understanding of some of this stuff.

Which is a cop out of course.
I am responsible for my own learning and while the method of procuring information does influence my ability to learn, I can use other strategies to learn the material more deeply.
So, I have used other strategies.
Repetition is one.
Writing things out by hand is another.
Trial and error yet another.
I know that the internet has some built in features that prevent deep learning, so I purposefully combat those features to make sure I have a solid knowledge and understanding of what I am learning.

It would be preposterous to suggest that the internet is not primarily responsible for my ability to make this career shift; in fact, it is almost solely responsible.
The point here is that the frustration I have had in this process is being buried in the amount of information, the uncurated nature of the presentation of this information, and the features embedded within the internet that actively discourage information from becoming genuine knowledge.

### Job Postings and Applications 

I have already hinted at some of the frustrations that lie in this area.
The long list of requirements or experience is daunting and leads me to question at what level do I need to know each and every item on the list.
Is it enough to know joins in SQL or do I need to know OLAP operators as well?
I can read Python scripts but I am not very good at writing them as of yet; does that mean I "know" Python?
I can make some really cool dashboards in Tableau...with the help of some online tutorials.
I might estimate my ability in each one of these areas as being too low (or too high) for the position, when in reality they might be looking for someone who simply knows the interface.
Well, yeah, I do; why didn't you just say that in the job posting then?
And circling back to another point made on this topic already; where does learning on the job come in?
I plan on continually taking online courses as I work to learn this stuff at an even deeper level.
Does that count for anything?

It is really discouraging to read a job posting for an entry level position that says "3-5 years experience required." How is this an entry level position then?
I start to fill out job applications and the dreaded "How many years of experience" question pops up.
There is usually a dropdown menu or a checkbox to click.
As soon as I select the "0 years" I feel like filling out the rest of the application is useless.
After that one click my application gets selectively removed by the AI and cast into the void.

The application process is also made more complicated by websites that don't work.
In the past two days, I have attempted to fill out two job applications...only to have the site have an issue.
One got halfway through and then just had half a page cut off and I couldn't move on until filling out that missing half a page.
Another got about 80% and when you clicked through to the next page it went nowhere.
Rocks in the shoe.
Big ones.

These frustrations are by no means confined to job searching in the field of data analytics: I had the same frustrations and feelings in education as well.
Same issues, same puzzled responses.
It seems to be simply the nature of trying to find a job in any industry.
Finding a job has probably never been easier with sites like LinkedIn, Indeed, ZipRecruiter, etc. but there are new complications and complexities that have arisen in this new environment as well.
We didn't eliminate all the viruses and bacteria, we just created new strains.

<br>

<br>

A career switch is a hero's journey.
At the end of this tale I will tower over a slayed Thanos on top of Mount Doom and have a new job in hand.
But on the way to that fulfilling end, there will be these bumps in the road, frustrations that pester.
Naming them is part of the process of conquering them.
