<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Andrew Borozan" />

<meta name="date" content="2022-03-28" />

<title>Elo Ratings</title>

<script src="site_libs/header-attrs-2.13/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/journal.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">The Unlikely Analyst</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./Markdown_Cyclistic_Final.html">Google Data Analytics Certification Project</a>
    </li>
    <li>
      <a href="./Reddit_Sentiment_Analysis_2_23.html">Sentiment Analysis with Reddit Comments</a>
    </li>
    <li>
      <a href="./Elo_rating.html">Accuracy of Elo Ratings</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Tutorials
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./Reactable_Walkthru.html">Reactable Tutorial</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Blog
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./I_am_crazy.html">"I am crazy" and other thoughts that flitter through my head.</a>
    </li>
    <li>
      <a href="./Frustrations_Along_the_Way.html">Frustrations Along the Way</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Just Following Along
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./TidyTuesday_Horror_Movies.html">Tidy Tuesday: Horror Movies</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/githubusername/mywebsite">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Elo Ratings</h1>
<h4 class="author">Andrew Borozan</h4>
<h4 class="date">2022-03-28</h4>

</div>


<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pacman)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">p_load</span>(tidyverse, skimr, scales, rmarkdown, magrittr, lubridate, janitor, ggrepel, ggthemes, showtext, knitr, reactable, palmerpenguins, car, broom, ggpubr, readxl, stringr, viridis, gghighlight)</span></code></pre></div>
<div id="how-good-are-elo-ratings-on-fivethirtyeight"
class="section level1">
<h1>How Good are Elo Ratings on FiveThirtyEight?</h1>
<p><a href="https://fivethirtyeight.com/">Fivethirtyeight.com</a> is
known for its stats heavy sports, politics, and societal analysis. Avid
sports fans might be familiar with Fivethirtyeight’s Elo ratings for
each of major sports leagues and college athletics. Using the Elo rating
model (originally used in chess), 538 (the numeric is so much easier to
type) rates teams in their respective sport and then uses the ratings to
predict the outcomes of games, series, and even entire seasons.</p>
<p>Here is a snapshot of what these Elo ratings look like and how they
are employed on 538:</p>
<p><img src="Images/paste-C4AE75F0.png" /></p>
<p>And then the Elo ratings are used to derive a win probability for
each team and predict a winner for each game.</p>
<p><img src="Images/paste-E6E4A726.png" /></p>
<p>Elo ratings have a lot of different factors that go into them. At its
most basic, the Elo rating is derived by looking at head to head matches
between teams for the entire season and looking at the point
differential of the final score. If the St. Louis Blues beat the
Colorado Avalanche 3-1 the Blues will experience an increase in their
Elo rating and the Avs will experience a decrease. Other things are
factored in, including home field/ice/court advantage, distance traveled
and, in some versions of Elo ratings, even injury status of players.</p>
<p>I stumbled across the project on Pat Schloss’s YouTube channel. He
analyzed baseball Elo ratings and their effectiveness at predicting the
winner of each game. I follow along with him for a while and then apply
the same analysis to the NHL Elo ratings and NFL Elo ratings. (I don’t
touch the NBA Elo ratings for two reasons: 1) They were not easily
accessible in the FiveThirtyEight Github repository, and 2) I don’t give
two craps about the NBA.)</p>
<div id="how-good-are-elo-ratings-for-baseball" class="section level2">
<h2>How good are Elo ratings for Baseball?</h2>
<p>The first thing we have to do, and this sounds a little nuts, is to
read in all game data in MLB history. Baseball began in 1871. That’s a
lot of games.</p>
<p>We load in the data and then look at what we just loaded.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mlb_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://projects.fivethirtyeight.com/mlb-api/mlb_elo.csv&quot;</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mlb_data)</span></code></pre></div>
<pre><code>## spec_tbl_df [223,427 x 26] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ date        : Date[1:223427], format: &quot;2021-11-02&quot; &quot;2021-10-31&quot; ...
##  $ season      : num [1:223427] 2021 2021 2021 2021 2021 ...
##  $ neutral     : num [1:223427] 0 0 0 0 0 0 0 0 0 0 ...
##  $ playoff     : chr [1:223427] &quot;w&quot; &quot;w&quot; &quot;w&quot; &quot;w&quot; ...
##  $ team1       : chr [1:223427] &quot;HOU&quot; &quot;ATL&quot; &quot;ATL&quot; &quot;ATL&quot; ...
##  $ team2       : chr [1:223427] &quot;ATL&quot; &quot;HOU&quot; &quot;HOU&quot; &quot;HOU&quot; ...
##  $ elo1_pre    : num [1:223427] 1571 1580 1578 1576 1566 ...
##  $ elo2_pre    : num [1:223427] 1575 1566 1568 1570 1580 ...
##  $ elo_prob1   : num [1:223427] 0.538 0.571 0.564 0.555 0.52 ...
##  $ elo_prob2   : num [1:223427] 0.462 0.429 0.436 0.445 0.48 ...
##  $ elo1_post   : num [1:223427] 1565 1575 1580 1578 1570 ...
##  $ elo2_post   : num [1:223427] 1581 1571 1566 1568 1576 ...
##  $ rating1_pre : num [1:223427] 1570 1569 1567 1565 1567 ...
##  $ rating2_pre : num [1:223427] 1566 1567 1569 1571 1569 ...
##  $ pitcher1    : chr [1:223427] &quot;Luis Garcia&quot; &quot;Tucker Davidson&quot; &quot;Dylan Lee&quot; &quot;Ian Anderson&quot; ...
##  $ pitcher2    : chr [1:223427] &quot;Max Fried&quot; &quot;Framber Valdez&quot; &quot;Zack Greinke&quot; &quot;Luis Garcia&quot; ...
##  $ pitcher1_rgs: num [1:223427] 52.6 47.2 47.4 54.1 53 ...
##  $ pitcher2_rgs: num [1:223427] 57.3 52.3 49.7 52.5 58.1 ...
##  $ pitcher1_adj: num [1:223427] 2.7 -30 -29.78 2.49 4.37 ...
##  $ pitcher2_adj: num [1:223427] 18.3213 0.0778 -11.6429 1.6237 20.5404 ...
##  $ rating_prob1: num [1:223427] 0.524 0.491 0.508 0.537 0.513 ...
##  $ rating_prob2: num [1:223427] 0.476 0.509 0.492 0.463 0.487 ...
##  $ rating1_post: num [1:223427] 1566 1566 1569 1567 1571 ...
##  $ rating2_post: num [1:223427] 1570 1570 1567 1569 1565 ...
##  $ score1      : num [1:223427] 0 5 3 2 7 2 4 5 11 2 ...
##  $ score2      : num [1:223427] 7 9 2 0 2 6 2 0 2 9 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   date = col_date(format = &quot;&quot;),
##   ..   season = col_double(),
##   ..   neutral = col_double(),
##   ..   playoff = col_character(),
##   ..   team1 = col_character(),
##   ..   team2 = col_character(),
##   ..   elo1_pre = col_double(),
##   ..   elo2_pre = col_double(),
##   ..   elo_prob1 = col_double(),
##   ..   elo_prob2 = col_double(),
##   ..   elo1_post = col_double(),
##   ..   elo2_post = col_double(),
##   ..   rating1_pre = col_double(),
##   ..   rating2_pre = col_double(),
##   ..   pitcher1 = col_character(),
##   ..   pitcher2 = col_character(),
##   ..   pitcher1_rgs = col_double(),
##   ..   pitcher2_rgs = col_double(),
##   ..   pitcher1_adj = col_double(),
##   ..   pitcher2_adj = col_double(),
##   ..   rating_prob1 = col_double(),
##   ..   rating_prob2 = col_double(),
##   ..   rating1_post = col_double(),
##   ..   rating2_post = col_double(),
##   ..   score1 = col_double(),
##   ..   score2 = col_double()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre>
<p>I am looking at this data during spring training, but if I were
looking at it in-season, I would want to filter for games that have
already been played. So, we will do that by default in case we run this
mid-season.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get only games that have already been played</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>mlb_data <span class="ot">&lt;-</span> mlb_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(date <span class="sc">&lt;</span> <span class="fu">Sys.Date</span>())</span></code></pre></div>
<p>This is where things are going to get a little complicated: for each
game, we need to find who the favorite was and whether they won. I will
comment through the code to explain what is happening throughout.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Who was the favorite for each game and did that team win?</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>favorite_win_prob_mlb <span class="ot">&lt;-</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  mlb_data <span class="sc">%&gt;%</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fav_538_won =</span> <span class="fu">ifelse</span>(elo_prob1 <span class="sc">&gt;</span> elo_prob2,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                              score1 <span class="sc">&gt;</span> score2, </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>                              score2 <span class="sc">&gt;</span> score1),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>         <span class="co"># Creates a TRUE/FALSE column to see if the favorite won. If the favorite won, the value will be TRUE. IF the favorite lost, the value will be FALSE. </span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">fav_538_prob =</span> <span class="fu">ifelse</span>(elo_prob1 <span class="sc">&gt;</span> elo_prob2, </span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>                               elo_prob1,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                               elo_prob2), </span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>         <span class="co"># Creates a column that has the probability of the favorite</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">favorite =</span> <span class="fu">ifelse</span>(elo_prob1 <span class="sc">&gt;</span> elo_prob2, </span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>                           team1,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>                           team2)) <span class="sc">%&gt;%</span> </span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Creates a column that identifies the favorite. Pat didn&#39;t have this but I found it helpful to identify. </span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(season, date, team1, team2, favorite, fav_538_prob, fav_538_won)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="co"># In the last step we select only the columns we are interested in. </span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(favorite_win_prob_mlb)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 7
##   season date       team1 team2 favorite fav_538_prob fav_538_won
##    &lt;dbl&gt; &lt;date&gt;     &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;lgl&gt;      
## 1   2021 2021-11-02 HOU   ATL   HOU             0.538 FALSE      
## 2   2021 2021-10-31 ATL   HOU   ATL             0.571 FALSE      
## 3   2021 2021-10-30 ATL   HOU   ATL             0.564 TRUE       
## 4   2021 2021-10-29 ATL   HOU   ATL             0.555 TRUE       
## 5   2021 2021-10-27 HOU   ATL   HOU             0.520 TRUE       
## 6   2021 2021-10-26 HOU   ATL   HOU             0.537 FALSE</code></pre>
<p>The best way to understand what is going is to look at the data
visually. We will create a line plot to see how the 538 Elo model has
performed since 1871. We want a line that denotes the mean for all time,
so we will create that first. The mean here is the fraction of time the
favorite won the game, or stated alternatively, the fraction of times
the model predicted the winner correctly. The mean line shows that the
model has done better than average (50%): It predicts the winner
correctly 57.48% of the time.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We want a line in our plot to show the average win probability of favorites for all time so we are going to get that value with this...</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>overall_win_prob_mlb <span class="ot">&lt;-</span> <span class="fu">mean</span>(favorite_win_prob_mlb<span class="sc">$</span>fav_538_won)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the fraction of games the favorite has won over time</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>favorite_win_prob_mlb <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(season) <span class="sc">%&gt;%</span> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">fraction_fav_won =</span> <span class="fu">mean</span>(fav_538_won)) <span class="sc">%&gt;%</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(season, fraction_fav_won)) <span class="sc">+</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept =</span> overall_win_prob_mlb), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))<span class="sc">+</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span><span class="st">&quot;Season&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Fraction of games favorite won&quot;</span>, </span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;The 538 model does a better than average job at predicting MLB games&quot;</span>, </span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">&quot;Since 1871, the favorite has won &quot;</span>, </span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">round</span>(overall_win_prob_mlb<span class="sc">*</span><span class="dv">100</span>, <span class="at">digits =</span> <span class="dv">2</span>), </span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>                         <span class="st">&quot;% of their games&quot;</span>))</span></code></pre></div>
<p><img src="Elo_rating_files/figure-html/unnamed-chunk-6-1.png" width="100%" /></p>
<p>What we want to do is plot the observed vs. expected fraction of
games won by the favorite. In other words, for all the times the
favorite had a 61% win probability, how many times did they actually
win? 61% percent? Lower? Higher? We are going to group each win
percentage (all the 51%s, all the 78%s….), see how many times this was
predicted, then see how many times the favorite actually win when they
had this particular win percentage.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>all_predicted_observed_mlb <span class="ot">&lt;-</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  favorite_win_prob_mlb <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fav_538_prob =</span> <span class="fu">round</span>(fav_538_prob, <span class="at">digits =</span> <span class="dv">2</span>)) <span class="sc">%&gt;%</span> <span class="co">#This makes grouping by the win probability possible. It would be impossible if we had the win probabilities at .63423294. We can group if they are at .63 though. </span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fav_538_prob) <span class="sc">%&gt;%</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">games =</span> <span class="fu">n</span>(), <span class="co"># Counts how many times this win probability for the favorite happened. </span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">wins =</span> <span class="fu">sum</span>(fav_538_won), <span class="co"># Counts how many times the favorite won</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">observed =</span> wins<span class="sc">/</span>games) <span class="co"># Gives the percentage of time predicted favorite won. </span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># You make a games played (trials) so you can use it in the binomial distribution later. You make wins and observed so you can plot them in relation to what it should be according to binomial distribution.</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Take a look at what this produces. </span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(all_predicted_observed_mlb)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   fav_538_prob games  wins observed
##          &lt;dbl&gt; &lt;int&gt; &lt;int&gt;    &lt;dbl&gt;
## 1         0.5  10517  5237    0.498
## 2         0.51 20497 10275    0.501
## 3         0.52 19683 10187    0.518
## 4         0.53 19651 10480    0.533
## 5         0.54 18802 10165    0.541
## 6         0.55 17614  9777    0.555</code></pre>
<p>A little analysis of this output:</p>
<ul>
<li><p>The win probability of the favorite is in the left most columns.
Think of these as “bins”, almost like in a histogram.</p></li>
<li><p>The next column has how many times that win probability was given
to the winner. For example, there have been 18,802 games when the
favorite has had the win probability of 54%.</p></li>
<li><p>Next, we have how many times the favorite actually won those
games. For the 18,802 games that were played where the favorite had a
54% chance of winning, they won 10,165 of those games.</p></li>
<li><p>The last column is simply the proportion of games won. 54.1% of
the time the team who had the win probability of 54% won the game…which
is exactly what you would expect. That means the model did a pretty good
job in this particular case.</p></li>
</ul>
<p>Finally, we want a visual representation for how well the observed
win percentage by win probability fits the predictions. We will make a
scatter plot that plots the win probability of the favorite (for
example, .54, .55, .56…) on the x-axis and the ratio of actual wins by
the favorite with that win probability on the y-axis (to continue the
example from above, we would plot 10,165/18,802, or .541, on the
y-axis). If the model is really good, we will see a pretty straight line
of points going trending upwards from left to right.</p>
<p>To add further insight on whether the model was accurate, we want to
see a 95% confidence interval ribbon on the graph as well. In the most
simple terms, the ribbon will tell us if the model was decent: if the
points lie in the shaded area, the model did a good job affixing a win
probability to the favorite: the model said the favorite would win 59%
of the time and the favorite won around 59% of the time. If many of the
points lie outside of the shaded area, the model needs tweaking. The
solid line shows what a perfect model would look like. For a brief
explanation of the binomial distribution and confidence intervals see
the footnote.<a href="#fn1" class="footnote-ref"
id="fnref1"><sup>1</sup></a></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We want to see the 95% confidence interval in the wins</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>binomial_fit_validation_mlb <span class="ot">&lt;-</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  all_predicted_observed_mlb <span class="sc">%&gt;%</span> </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prob =</span> fav_538_prob) <span class="sc">%&gt;%</span> </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Need to put prob in the nested tibbled rows</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fav_538_prob) <span class="sc">%&gt;%</span> </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>() <span class="sc">%&gt;%</span> <span class="co"># This puts each row in its own tibble</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">binomial =</span> <span class="fu">map</span>(data, <span class="cf">function</span>(df) <span class="co"># map() takes the nested data and runs it through the function we are about to invoke</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tidy</span>(<span class="fu">binom.test</span>(<span class="at">x =</span> <span class="fu">as.integer</span>(df<span class="sc">$</span>games <span class="sc">*</span> df<span class="sc">$</span>prob), </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>                    <span class="at">n =</span> df<span class="sc">$</span>games, </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">p =</span> df<span class="sc">$</span>prob)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>               ) <span class="co"># We are peforming a binomial test on each row of the data, meaning each win probability - .51, .52... - to determine the 95% confidence interval for each win probability. Tidy() puts our statistical findings - like the p-value and 95% confidence interval - into a tibble. </span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span> </span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>() <span class="sc">%&gt;%</span> <span class="co">#unnest gets all of the data out of the tibble and puts it into each row.</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(fav_538_prob, games, wins, observed, conf.low, conf.high)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a><span class="co"># We don&#39;t need all of the information from the binom.test - like parameter and statistic - so we just choose the ones that are pertinent. </span></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Now, let&#39;s build a graph that shows the actual win percentage by favorite&#39;s win probabilities (the points on the graph). Again, the points will show the percentage of times the favorite with a particular win probability (say, .65) actually won. </span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="co"># The solid line shows a perfect model - the model predicted the favorite .61 of the time and they actually won 61% of the time. </span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="co"># The shaded region shows the 95% confidence interval. The model is pretty good if the points are within that shaded region.</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>binomial_fit_validation_mlb <span class="sc">%&gt;%</span> </span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(fav_538_prob, observed)) <span class="sc">+</span></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> conf.low, <span class="at">ymax =</span> conf.high), <span class="at">fill =</span> <span class="st">&quot;indianred1&quot;</span>, <span class="at">alpha =</span> .<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept=</span> <span class="dv">0</span>, <span class="at">slope=</span><span class="dv">1</span>), <span class="at">color =</span> <span class="st">&quot;indianred3&quot;</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()<span class="sc">+</span></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;The favorite&#39;s win probability before game was played&quot;</span>, </span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Proportion of games the favorite won&quot;</span>, </span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;How well does FiveThirtyEight&#39;s Elo ratings do at predicting MLB games?&quot;</span>)</span></code></pre></div>
<p><img src="Elo_rating_files/figure-html/unnamed-chunk-8-1.png" width="100%" /></p>
<p>The goal is for the point (dot) to be right on the line. That means
that the model predicts the outcome perfectly. If you predicted the
favorite to have a win probability of .67 and they win 67% of the time
that means you are spot on in your prediction. Points above the line
mean that you are under-predicting the win probability. You are
predicting the favorite is going to win 67% of the time and they are
actually winning 78% of the time. Over or under predicting significantly
means your model needs tweaking. What is “significantly” here? That is
what the confidence interval (the shaded region) is for. It is not too
uncommon for a team to win 52% of their games when they are predicted to
win 53% of the time. It is unreasonable for them to win 78% of their
games when they are predicted to win 53% though. Therefore, the
confidence interval is the range of acceptability. If the point is
within that range, it means the prediction was reasonable.</p>
<p>As seen in the graph, the FiveThirtyEight Elo ratings for baseball
have been historically very good. They slightly under sell the favorite
most of the time, but the model demonstrates a pretty good fit to the
actual data.</p>
<p>Can the same be said for their hockey Elo ratings? Let’s find
out.</p>
</div>
<div id="how-good-are-elo-ratings-for-hockey" class="section level2">
<h2>How good are Elo ratings for Hockey?</h2>
<p>We are going to go through the same steps as above. This should move
a little more quickly as we get rid of all of the explanation of what is
happening in between.</p>
<p>Read in the data, graciously provided by FiveThirtyEight.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>nhl_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://projects.fivethirtyeight.com/nhl-api/nhl_elo.csv&quot;</span>)</span></code></pre></div>
<p>As the season is currently in session, we filter out yet to be played
games.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>nhl_data <span class="ot">&lt;-</span> nhl_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(date <span class="sc">&lt;</span> <span class="fu">Sys.Date</span>())</span></code></pre></div>
<p>Perform the same transformation as we did for the MLB data: create
columns for the favorite win probability and identify whether the
favorite won or not.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Who was the favorite for each game and did that team win?</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>favorite_win_prob_nhl <span class="ot">&lt;-</span> nhl_data <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fav_538_won =</span> <span class="fu">ifelse</span>(home_team_winprob <span class="sc">&gt;</span> away_team_winprob,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                              home_team_score <span class="sc">&gt;</span> away_team_score, </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                              away_team_score <span class="sc">&gt;</span> home_team_score),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>         <span class="co"># Creates a TRUE/FALSE column to see if the favorite won</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">fav_538_prob =</span> <span class="fu">ifelse</span>(home_team_winprob <span class="sc">&gt;</span> away_team_winprob, </span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                               home_team_winprob,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>                               away_team_winprob), </span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>         <span class="co"># Creates a column that has the prob of the favorite</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">favorite =</span> <span class="fu">ifelse</span>(home_team_winprob <span class="sc">&gt;</span> away_team_winprob, </span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>                           home_team_abbr,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>                           away_team_abbr)) <span class="sc">%&gt;%</span> </span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Creates a column that identifies the favorite</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(season, date, home_team, away_team, favorite, fav_538_prob, fav_538_won)</span></code></pre></div>
<p>Let’s see how the NHL Elo ratings have done over time in predicting
the winner.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We want a line in our plot to show the average win prob of favorites for all time</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># so we are going to get that value with this...</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>overall_win_prob_nhl <span class="ot">&lt;-</span> <span class="fu">mean</span>(favorite_win_prob_nhl<span class="sc">$</span>fav_538_won)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the fraction of games the favorite has won over time</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>favorite_win_prob_nhl <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(season) <span class="sc">%&gt;%</span> </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">fraction_fav_won =</span> <span class="fu">mean</span>(fav_538_won)) <span class="sc">%&gt;%</span> </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(season, fraction_fav_won)) <span class="sc">+</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept =</span> overall_win_prob_nhl), <span class="at">color =</span> <span class="st">&quot;green3&quot;</span>) <span class="sc">+</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))<span class="sc">+</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span><span class="st">&quot;Season&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Fraction of games favorite won&quot;</span>, </span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;The 538 model does a better than average job at predicting NHL games&quot;</span>, </span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">&quot;Since 1917, the favorite has won &quot;</span>, </span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">round</span>(overall_win_prob_nhl<span class="sc">*</span><span class="dv">100</span>, <span class="at">digits =</span> <span class="dv">2</span>), </span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>                        <span class="st">&quot;% of their games&quot;</span>))</span></code></pre></div>
<p><img src="Elo_rating_files/figure-html/unnamed-chunk-12-1.png" width="100%" /></p>
<p>At predicting the winners, the Elo ratings do a fairly good job -
better than a coin flip at least. They mirror the baseball prediction of
winners.</p>
<p>Now let’s take a look at the accuracy of the model. how well has the
model done in affixing win probabilities to favorites?</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>all_predicted_observed_nhl <span class="ot">&lt;-</span> favorite_win_prob_nhl <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fav_538_prob =</span> <span class="fu">round</span>(fav_538_prob, <span class="at">digits =</span> <span class="dv">2</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fav_538_prob) <span class="sc">%&gt;%</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">games =</span> <span class="fu">n</span>(), </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">wins =</span> <span class="fu">sum</span>(fav_538_won), </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">observed =</span> wins<span class="sc">/</span>games) </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># You make a games played (trials) so you can use it in the binomial distribution later. You make wins and observed so you can plot them in relation to what it should be according to binomial distribution.</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co"># We want to see the 95% confidence interval in the wins</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>binomial_fit_validation_nhl <span class="ot">&lt;-</span> all_predicted_observed_nhl <span class="sc">%&gt;%</span> </span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prob =</span> fav_538_prob) <span class="sc">%&gt;%</span> </span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Need to put prob in the nested tibbled rows</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fav_538_prob) <span class="sc">%&gt;%</span> </span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>() <span class="sc">%&gt;%</span> <span class="co"># This puts each row in its own tibble</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">binomial =</span> <span class="fu">map</span>(data, <span class="cf">function</span>(df)</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">tidy</span>(<span class="fu">binom.test</span>(<span class="at">x =</span> <span class="fu">as.integer</span>(df<span class="sc">$</span>games <span class="sc">*</span> df<span class="sc">$</span>prob), </span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">n =</span> df<span class="sc">$</span>games, </span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">p =</span> df<span class="sc">$</span>prob)</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>                             )</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>                        )</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span> </span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(fav_538_prob, games, wins, observed, conf.low, conf.high)</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(binomial_fit_validation_nhl, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 6
## # Groups:   fav_538_prob [10]
##    fav_538_prob games  wins observed conf.low conf.high
##           &lt;dbl&gt; &lt;int&gt; &lt;int&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
##  1         0.5   1892   848    0.448    0.477     0.523
##  2         0.51  3697  1747    0.473    0.494     0.526
##  3         0.52  3582  1691    0.472    0.503     0.536
##  4         0.53  3775  1802    0.477    0.514     0.546
##  5         0.54  3732  1835    0.492    0.524     0.556
##  6         0.55  3605  1871    0.519    0.533     0.566
##  7         0.56  3604  1867    0.518    0.544     0.576
##  8         0.57  3472  1833    0.528    0.553     0.587
##  9         0.58  3406  1817    0.533    0.563     0.597
## 10         0.59  3305  1802    0.545    0.573     0.607</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>binomial_fit_validation_nhl <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(fav_538_prob, observed)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> conf.low, <span class="at">ymax =</span> conf.high), <span class="at">fill =</span> <span class="st">&quot;lawngreen&quot;</span>, <span class="at">alpha =</span> .<span class="dv">4</span>)<span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept=</span> <span class="dv">0</span>, <span class="at">slope=</span><span class="dv">1</span>), <span class="at">color =</span> <span class="st">&quot;green4&quot;</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))<span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;The favorite&#39;s win probability before game was played&quot;</span>, </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Proportion of games the favorite won&quot;</span>, </span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;How well does FiveThirtyEight&#39;s Elo ratings do at predicting NHL games?&quot;</span>)</span></code></pre></div>
<p><img src="Elo_rating_files/figure-html/unnamed-chunk-13-1.png" width="100%" /></p>
<p>This is a little underwhelming. The graph shows that the model
over-predicts the win probability. When it predicts the favorite has a
win probability of 54%, the favorite only wins 49% of the time (outside
the acceptable confidence interval). Win the favorite is predicted to
have a win probability of .5 to .7, the model is missing the mark; the
favorite wins at a lesser clip than the predicted win probability. The
model would need an adjustment, especially on the lower end of predicted
win probabilities, for it to be robust.</p>
</div>
<div id="how-good-are-elo-ratings-for-footall" class="section level2">
<h2>How good are Elo ratings for Footall?</h2>
<p>And now for the NFL. Read in the data….</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>nfl_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://projects.fivethirtyeight.com/nfl-api/nfl_elo.csv&quot;</span>)</span></code></pre></div>
<p>And clean it up.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>nfl_data <span class="ot">&lt;-</span> nfl_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(date <span class="sc">&lt;</span> <span class="fu">Sys.Date</span>())</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>favorite_win_prob_nfl <span class="ot">&lt;-</span> nfl_data <span class="sc">%&gt;%</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fav_538_won =</span> <span class="fu">ifelse</span>(elo_prob1 <span class="sc">&gt;</span> elo_prob2,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                              score1 <span class="sc">&gt;</span> score2, </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                              score2 <span class="sc">&gt;</span> score1),</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>         <span class="co"># Creates a TRUE/FALSE column to see if the favorite won</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">fav_538_prob =</span> <span class="fu">ifelse</span>(elo_prob1 <span class="sc">&gt;</span> elo_prob2, </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>                               elo_prob1,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>                               elo_prob2), </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>         <span class="co"># Creates a column that has the prob of the favorite</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">favorite =</span> <span class="fu">ifelse</span>(elo_prob1 <span class="sc">&gt;</span> elo_prob2, </span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>                           team1,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>                           team2)) <span class="sc">%&gt;%</span> </span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Creates a column that identifies the favorite</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(season, date, team1, team2, favorite, fav_538_prob, fav_538_won)</span></code></pre></div>
<p>Let’s see how the NHL Elo ratings have done over time in predicting
the winner.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We want a line in our plot to show the average win prob of favorites for all time so we are going to get that value with this...</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>overall_win_prob_nfl <span class="ot">&lt;-</span> <span class="fu">mean</span>(favorite_win_prob_nfl<span class="sc">$</span>fav_538_won)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the fraction of games the favorite has won over time</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>favorite_win_prob_nfl <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(season) <span class="sc">%&gt;%</span> </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">fraction_fav_won =</span> <span class="fu">mean</span>(fav_538_won)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(season, fraction_fav_won)) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept =</span> overall_win_prob_nfl), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))<span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span><span class="st">&quot;Season&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Fraction of games favorite won&quot;</span>, </span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;The 538 model does a better than average job at predicting NFL games&quot;</span>, </span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">&quot;Since 1920, the favorite has won &quot;</span>, </span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">round</span>(overall_win_prob_nfl<span class="sc">*</span><span class="dv">100</span>, <span class="at">digits =</span> <span class="dv">2</span>), </span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>                         <span class="st">&quot;% of their games&quot;</span>))</span></code></pre></div>
<p><img src="Elo_rating_files/figure-html/unnamed-chunk-16-1.png" width="100%" /></p>
<p>The Elo ratings shine brightly at picking the winners for NFL games.
At 65% they are better than both baseball and hockey.</p>
<p>Now let’s take a look at the accuracy of the model. how well has the
model done in affixing win probabilities to favorites?</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>all_predicted_observed_nfl <span class="ot">&lt;-</span> favorite_win_prob_nfl <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fav_538_prob =</span> <span class="fu">round</span>(fav_538_prob, <span class="at">digits =</span> <span class="dv">2</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fav_538_prob) <span class="sc">%&gt;%</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">games =</span> <span class="fu">n</span>(), </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">wins =</span> <span class="fu">sum</span>(fav_538_won), </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">observed =</span> wins<span class="sc">/</span>games) </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co"># We want to see the 95% confidence interval in the wins</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>binomial_fit_validation_nfl <span class="ot">&lt;-</span> all_predicted_observed_nfl <span class="sc">%&gt;%</span> </span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prob =</span> fav_538_prob) <span class="sc">%&gt;%</span> </span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fav_538_prob) <span class="sc">%&gt;%</span> </span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>() <span class="sc">%&gt;%</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">binomial =</span> <span class="fu">map</span>(data, <span class="cf">function</span>(df)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tidy</span>(<span class="fu">binom.test</span>(<span class="at">x =</span> <span class="fu">as.integer</span>(df<span class="sc">$</span>games <span class="sc">*</span> df<span class="sc">$</span>prob), </span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>                    <span class="at">n =</span> df<span class="sc">$</span>games, </span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>                    <span class="at">p =</span> df<span class="sc">$</span>prob)</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(fav_538_prob, games, wins, observed, conf.low, conf.high)</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>binomial_fit_validation_nfl <span class="sc">%&gt;%</span> </span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(fav_538_prob, observed)) <span class="sc">+</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> conf.low, <span class="at">ymax =</span> conf.high), <span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>)<span class="sc">+</span></span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept=</span> <span class="dv">0</span>, <span class="at">slope=</span><span class="dv">1</span>), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))<span class="sc">+</span></span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>   <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;The favorite&#39;s win probability before game was played&quot;</span>, </span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Proportion of games the favorite won&quot;</span>, </span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;How well does FiveThirtyEight&#39;s Elo ratings do at predicting NFL games?&quot;</span>)</span></code></pre></div>
<p><img src="Elo_rating_files/figure-html/unnamed-chunk-17-1.png" width="100%" /></p>
<p>The 95% confidence interval is slightly larger for the NFL because of
far fewer games played (see the footnote for a bit more explanation).
Keeping that in mind, it still fairly impressive that almost all of the
points are within that 95% band. The Elo ratings for the NFL seem to be
working: when the model predicts teams will win 71% of the time, the win
almost 71% of the time.</p>
<p>Fivethirtyeight’s Elo ratings stand up to scrutiny. They might not be
the most useful tool for betting purposes, but for general sports fan,
they can predict with fairly decent accuracy, a winner and can pinpoint
with some degree of accuracy the win probability of the favorite.</p>
</div>
</div>
<div class="footnotes footnotes-end-of-document">
<hr />
<ol>
<li id="fn1"><p>In the code chunk below the footnote we use the binomial
distribution to determine a 95% confidence interval for each win
probability.</p>
<p>The binomial test used takes the number of successes (in our case,
<em>wins</em>), the number of trials (in our case, <em>games</em>), and
the probability of success (in our case, <em>win probability</em>). It
then calculates the odds of getting that many successes in that many
trials based on the probability of success.</p>
<p>For example: What is the probability of winning 65 games out of 100
when the win probability is 51%? You use the binomial test to determine
the probability of winning 65 games in 100 when the win probability is
51%.</p>
<p>binom.test(x = 65, n = 100, p = .51)</p>
<p>This will return a p-value of .005. That means there is a .5% chance
of winning 65 games out of 100 - very low.</p>
<p>Ok, so what win probability would I need to get 65 wins out of 100?
51% is way too low to be confident that I would get 65 wins out of 100.
I need some sort of win probability range where 65 wins out of a 100 is
very possible.</p>
<p>That range is the confidence interval. The confidence interval
(provided when we run the binom.test) tells us that most of the time
(95% of the time) 65 wins out of a 100 usually comes with a win
probability of between 54% and 74%.</p>
<p>Stated another way, to get 65 wins out of a 100 you would need
between a 54% and 74% win probability.</p>
<p>That is actually a pretty wide range. The more trials you run, the
more precise this gets. Watch if we increase this example by a factor of
10.</p>
<p>binom.test(x = 650, n = 1000, p = .51)</p>
<p>The 95% confidence interval - the range where you are going to get
most of the times you win 650 times - narrows to .619 - .679.</p>
<p>This is important for our case here, seeing as there are many, many
games, especially for the win probabilities from .50 to about .71. For
example, there are close to 20,500 games where the favorite had a win
probability of .51. Once we start getting to where the favorite had a
win probability of .72, we dip below a 1000 games. We only have 9 games
in the history of major league baseball where the favorite had a win
probability of .82. On the graph then, you will see the gray confidence
interval ribbon go berserk. With that few trials, the range of the win
probability you would need to confidently get 8 wins in 10 is very wide.
It is not too out of the realm of possibility that the team with a 30%
of winning wins 8 out of 10. It is far more likely they win 8 out of 10
than 800 out of 1000.</p>
<p>In sum, we use the binom.test() function to calculate the 95%
confidence interval for each win probability. This 95% confidence
interval says “95% of the time, you are going to hit your win
probability between this number ___ and this number ___.” Looking at our
results, 95% of the time a .52 win probability hits between .513 and
.527.</p>
<p>Therefore, any “observed” win probability - actual proportion of
games won to games played - that lies outside of the 95% interval is
very unlikely to happen. That doesn’t mean the game itself is wrong, it
means the model did not predict the win probability of the favorite very
well.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
